# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 253a8455c5b36e12fd691240f73fc16d09f91e3a60a2d146214c590db5581edf522891eb0f9f52d7dc1edf5def04682a38443528b5bf7cde6df89503c0639e61

test:
  secret_key_base: 53375a56980521c16f880a1376014b6b49ad9b4eba6aecc32a823fd760a84f8a0dc6ec8ea8de7aa02aa93212d8eee3b097d2a4652f95ce6704d9f6a37fb88cc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
